openapi: 3.1.1
info:
  title: Fika Collect Lambda API
  version: 1.0.0
paths:
  /generate-upload-url:
    post:
      summary: Generate a pre-signed upload URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_type:
                  type: string
                  required: true
                  description: The type of the file to be uploaded
                  enum:
                    - image/jpeg
                    - image/webp
                    - image/heic
                    - image/png
                survey_id:
                  type: string
                  required: true
                  description: The ID of the survey associated with the file
              required:
                - file_type
                - survey_id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  uploadURL:
                    type: string
                    description: The pre-signed URL for file upload
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
