version = 0.1
[default.deploy.parameters]
stack_name = "fika-collect-upload-signer"
resolve_s3 = true
s3_prefix = "fika-collect-upload-signer"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
