AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda based services for Fika Collect
Resources:
  fikaCollectUploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: 'Fika Collect upload Lambda'
      MemorySize: 128
      Timeout: 3
      Handler: handler.presignUpload
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObjectAcl
                - s3:GetObject
                - s3:ListBucket
                - s3:PutObjectAcl
              Resource: arn:aws:s3:::fika-collect
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  fikaCollectSurveySubmitLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: 'Fika Collect survey submission lambda'
      MemorySize: 128
      Timeout: 3
      Handler: handler.submitSurvey
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObjectAcl
                - s3:GetObject
                - s3:ListBucket
                - s3:PutObjectAcl
              Resource: arn:aws:s3:::fika-collect
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
