AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  GenerateUploadURLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: nodejs14.x
      CodeUri: .
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          AWS_REGION: !Ref AWS::Region
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-upload-url
            Method: post
Outputs:
  GenerateUploadURLFunction:
    Description: 'Generate Upload URL Lambda Function ARN'
    Value: !GetAtt GenerateUploadURLFunction.Arn
  ApiUrl:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-upload-url'
